event_params:
  frequency_seconds: 2
  input_data_file: input_data/simulation.json
  devices_path: devices
  backup_path: backup
  range_of_files:
    min: 2
    max: 5

logging:
  log_location: logs
  log_format: "%Y%m%d%H%M%S"
  logger_level: 20

utils:
  custom_format: "%d%m%y%H%M%S"
